### ISSUE TITLE
When will the code be released?

### ISSUE THREAD

**Issue by SYSUGrain** [aevainc/carla#2]
Thanks for your great work. I'd like to know when will the code be released?

**Comment by SYSUGrain** [comment]
I visualize the carla data, and it seems that it only contains static scenes. I wanna know whether your simulation can simulate the dynamic scenes which contain moving NPCs. Thanks a lot.

**Comment by heethesh** [comment]
Yes, our simulation works on all NPC actors to get the per-point Doppler velocity returns.

**Comment by SYSUGrain** [comment]
Wow! Fantastic! Great work!

**Comment by heethesh** [comment]
Available here now: https://github.com/aevainc/carla-aeva
