### ISSUE TITLE
Why "available soon" is so long?

### ISSUE THREAD

**Issue by cuge1995** [aevainc/carla#3]

**Comment by heethesh** [comment]
Available here now: https://github.com/aevainc/carla-aeva

**Comment by HelloDuoLA** [comment]
> Available here now: https://github.com/aevainc/carla-aeva

How to use FMCW Lidar in it? I can't find the instructions.

**Comment by heethesh** [comment]
Pending internal review, please check back tomorrow EOD. We have a Python example to demonstrate the usage

**Comment by HelloDuoLA** [comment]
> Pending internal review, please check back tomorrow EOD. We have a Python example to demonstrate the usage

Can you give me the path to this file? I still haven't found it

**Comment by heethesh** [comment]
@HelloDuoLA please see the updated README file.
