### ISSUE TITLE
Some problems about ScanPattern.h

### ISSUE THREAD

**Issue by kahowang** [aevainc/carla#4]
Hello, thanks for your great work. @heethesh 
I have some questions regarding the Carla-Aeva simulation that I would like to consult about:

1、Based on the [ScanPattern.h](https://github.com/aevainc/carla-aeva/blob/aeva-lidar-plugin/ScanPatterns.yaml) file, I have calculated the vertical FOV of the simulated Aeva lidar to be 18.737 degrees. Here is my calculation method: 
`Maximum vertical angle: 1.718873 + 7.5`
`Minimum vertical angle: -1.718873 - 7.8`
`Vertical FOV = 1.718873 + 7.5 + 1.718873 + 7.8 = 18.737746 degrees.`

However, in the code comments  :

>   ```
>   patterns:
>     # This scan pattern has a uniform distribution of 64 total lines and 19.2 degrees of vertical FoV.
>     64-19.2-Uniform:, 
>   ```

it is mentioned that the lidar'svertical FoV is 19.2°. I'm wondering if there might be a misunderstanding on my part regarding the vertical FOV of 19.2 degrees? Could you please clarify this?

2、I have a question regarding the FMCW LIDAR sensor configuration as described in the [ref_sensor.md](https://github.com/aevainc/carla-aeva/blob/aeva-lidar-plugin/Docs/ref_sensors.md#fmcw-lidar-sensor) document, specifically in the **RAYCAST_PER_POINT** section. The document includes an image with the caption: 

> "Note you can see the simultaneous scanning of the 32 channels from each of 4 beams of this scan pattern."
![image](https://github.com/aevainc/carla/assets/35909921/5b894c92-ef5a-474a-81c1-10afa53daf78)

 However, based on my understanding of the ScanPattern.h and FMCWLidarPattern.cpp files. In my opinion the simulataneous scanning of the **16** channels from each of 4 beams of **64-19.2-Uniform** scan pattern. Could you please clarify if there is a discrepancy between the document and the implementation or if I am misunderstanding the configuration?

Looking forward for your reply.
Best regards, 
kaho

**Comment by heethesh** [comment]
Hi @kahowang, I'm tagging @jxu-aeva here who might be able to better assist you this.

**Comment by kahowang** [comment]
Hello, heeethesh @heethesh 

Could you please help me get in touch with @jxu-aeva? I believe he might have missed my previous messages, and I would like to discuss more about the Aeva-LiDAR CARLA simulation project. I am keen to understand more about this topic as soon as possible. Thank you for your assistance.

Best regards,
Kaho

**Comment by heethesh** [comment]
Hi @kahowang, @jxu-aeva will soon respond to your original query. For any other queries about this simulation project, please follow up on the Jira portal. We have a ticket created there for this issue, let me know if you cannot access it. Thanks!

**Comment by jxu-aeva** [comment]
Hi @kahowang. Thanks, these are good questions.

Re. 1:
Your calculations are correct, and the 18.7 degrees will be the vertical FoV in the simulation. The "19.2" value stems from our naming conventions, and refers to a nominal value assuming beam elevation offsets different from the default. We'll update the comment to reflect this.

Re. 2:
If we are operating in **RAYCAST_PER_POINT** mode, the number of simultaneous points scanned per time-step is independent of the scan pattern. The **channels** term refers to the number of threads, not the number of lines. We will change or adjust the terminology to make this more clear.

In [this line](https://github.com/aevainc/carla-aeva/blob/7c9a95a960c70de1c0edd1fba8ec615711fff52d/Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/FMCWLidar.cpp#L135C59-L135) we specify a parallel for-loop based on the predefined number of threads.
In [these lines](https://github.com/aevainc/carla-aeva/blob/7c9a95a960c70de1c0edd1fba8ec615711fff52d/Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/FMCWLidar.cpp#L144-L145) we specify which portion out of the entire set of azimuth+elevation angles that each thread will raycast this timestep. In [FMCWLidarPattern.h](https://github.com/aevainc/carla-aeva/blob/7c9a95a960c70de1c0edd1fba8ec615711fff52d/Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/FMCWLidarPattern.h#L133) each thread will raycast exactly one point in **RAYCAST_PER_POINT** mode. So 32 channels will raycast 32 points simultaneously per beam (32x4 total).
